language: python
cache: pip

# Supported CPython versions:
# https://en.wikipedia.org/wiki/CPython#Version_history
python:
 - pypy3
 - 3.6

install:
 - pip install -U pip
 - pip install -U black flake8

script:
 # Static analysis
 - flake8 --statistics --count
 - black --check --diff .

 # Validate
 - python validate-json.py

matrix:
  fast_finish: true
